In [2]:
from datascience import *
import numpy as np
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update(
    "livereveal", {
        "width": "90%",
        "height": "90%",
        "scroll": True,
})

{'width': '90%', 'height': '90%', 'scroll': True}

# DSC 10 Discussion Week 1
---

This discussion section is meant to cover some of the basics of Python that you've seen so far in this class.

If at any point you have a question, feel free to ask

## Jupyter Notebook Shortcuts

shift+enter: run cell and move focus to cell below <br>
ctl+enter: run cell and keep focus on cell <br>

Command Mode (cell is blue):<br>
x: cut the cell, also quick way to delete<br>
c: copy the cell<br>
v: paste the cell<br>
d+d: delete cell<br>
a: make new cell above<br>
b: make new cell below<br>
y: change cell to code<br>
m: change cell to markdown<br>
enter: start editing cell<br>

Editing Mode (cell is green):<br>
esc: enter command mode<br>
shift+tab: info about a function<br>

# What we'll cover tonight:
---

- What is Python?
- Data Types
- Variables
- Functions
- Creating a Table

# What is Python?
---

Python is a **high-level**, **interpreted** programming language invented by Guido Van Rossum in 1991.  It is a powerful language while remaining **dynamically-typed**, easily **readable**, and has plenty of **whitespace**.

- High-level:
  - Don't need to worry about giving instructions to the computer

- Interpreted:
  - A file or cell can run instantly; does not need to compile to another file

- Dynamically Typed:
  - Python infers what type you want a variable to be; you don't tell it explicitly

In [4]:
x = "this is a string"
print(x)

x = 1.2
print(x)

x = False
print(x)

this is a string
1.2
False


- Readable:
  - Simply reading code aloud should largely reveal what's going on

- Whitespace:
  - You can *and should* use multiple lines to fit the `Python a e s t h e t i c`

# Data Types in Python
---

Everything in Python has a type.

Some things are really simple—you could call them *"primitive"*.  
These things have a specific value.

There are four types of primitives:
- Integers (ex. 1, 2, -12)
- Floats (ex. 1.0, 3.5, -0.34)
- Strings ("this is a string", "a", "b")
- Booleans (True, False)

Other things are a bit more complex.  
These things act more like containers for values (or more containers).

Some examples include:
- Lists
- Arrays
- Tables
- Dictionaries
- Sets

### Primitive Types: integers, floats, strings, booleans

In [5]:
# Integers
type(65)

int

In [8]:
# Floats
type(1.0)

float

In [12]:
# Strings
type("Hello")

str

In [13]:
# Booleans (True or False)
type(False) 

bool

What are some things we can do with these primitive types?

In [14]:
# Let's do some testing together... here's a couple to start with:

3 + 5 # Can we do this?

8

In [15]:
3 + 5.9876 # What about this?

8.9876

In [16]:
# How about this?
3 + "string"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [18]:
# or this?
"string" + "another string"

'stringanother string'

### Some Others: arrays, and tables

In [22]:
# Lists
# type([[5,2,'hello'], '1', 2, '3']) # Lists can contain any type of data
['hi', ['how', 'are', 'you']]

['hi', ['how', 'are', 'you']]

In [26]:
l = [1, 2, 3] # I want to add 4 to this list
# We can use np.append to do this!
l.append(4)
l

[1, 2, 3, 4]

In [27]:
# NumPy Arrays
import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [28]:
# NumPy Arrays will fit all data to **the same type**
print("overall type:", type(np.array([1, 2, 3])))
print("type of individual elements:", np.array([1, 2, 3]).dtype)

overall type: <class 'numpy.ndarray'>
type of individual elements: int32


In [30]:
# Can also create NumPy array with 'make_array'

# We need to import datascience first
from datascience import *

type(make_array(1, 2, 3)) # This is the same as before! 
#! IMPORTANT:  np.array takes a LIST, but make_array takes INDIVIDUAL VALUES  

numpy.ndarray

In [31]:
make_array(2, 1)

array([2, 1])

In [36]:
make_array(1, 3, 1.2, 1, 4)

array([1. , 3. , 1.2, 1. , 4. ])

Recap:

All objects in Python have a type, some of which are primitive, some of which act more like containers.

If we ever forget what type something is, we can use `type()` to find out!

# Variables
---

In Python when you assign a variable like this:

`x = 4 + 3`

You're essentially telling Python this:

`From now on, please let the value of 'x' contain the value of 7.`

In [37]:
x = 4
y = "Why"
z = [4.0, "That's the dream..."]
class_choice = make_array("Cake", 3.14)

print(x)
print(y)
print(z)
print(class_choice) 

4
Why
[4.0, "That's the dream..."]
['Cake' '3.14']


What happens if we assign x again?

In [38]:
print(x)

4


In [39]:
x = "string"
print(x)

string


Recall that variables assume the type of what you assign it to

In [40]:
print(type(x))
print(type(y))
print(type(z))
print(type(class_choice))

<class 'str'>
<class 'str'>
<class 'list'>
<class 'numpy.ndarray'>


We can even assign variables to other variables, this can get a bit tricky.

In [42]:
x = 1
y = x
x = 2

print("y == x?       ", y == x)

y == x?        False


Wait but I thought we just set `y = x`!

Recall that we're telling Python to assign y **to the value of** x, not directly to x!

What is the value of something then?
It's whatever is returned if you run it at the end of a cell.

In [43]:
# The value of x is
x

2

# Functions
---

Functions, like `print()`, allow us to easily run something with different <b>arguments</b>.

We can also define our own functions to allow us to run our own code multiple times with different arguments.

### Definitions:
<b>Parameter</b>: Variable in method definition. Ex: `def print(string_to_print):`

<b>Argument</b>: Actual value used in function calls. Ex: `print("hello")`

Kinda pedantic, they are often used interchangably and people will know what you mean either way.

Many functions take values as inputs.  
All functions will return a value (but that value may be `None`).

Just like all values in Python, these have a type!

So, it's important that we know what a function takes and what it returns.

This helps a lot when it comes to fixing bad code!

A Python function is called with the following format:

`function_name(arg_1, arg_2, ...)`

For example, `sum` takes a list (or array-like object) as a argument.  
The function `len` can take a list too.

In [44]:
sum(make_array(1, 2, 3))

6

In [45]:
len(make_array(1, 2, 3))

3

And other functions, like `pow` take more than one argument.

In [46]:
help(pow)

Help on built-in function pow in module builtins:

pow(x, y, z=None, /)
    Equivalent to x**y (with two arguments) or x**y % z (with three arguments)
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [49]:
pow(1.618, 2)

2.6179240000000004

Some objects have their own functions!  
To call this, you need to use "dot notation", it looks like this:


`some_object.func_name(some_arg_1, some_arg_2, ...)`

In [56]:
tbl = Table()
tbl = tbl.with_column("Hello", make_array("wow", "that's", "cool")).with_column("Goodbye", ":(").with_column("hello",":)")

tbl

Hello  | Goodbye | hello
wow    | :(      | :)
that's | :(      | :)
cool   | :(      | :)

We can assign a variable as the result of a function the same way we assign any variable!

In [57]:
x = pow(8, 2)
x

64

<b>Bonus Question</b>: What is the return type of `print("hello")`?

In [58]:
x = print("hello")
type(x)

hello


NoneType

<b>Bonus Bonus Question</b>: What will be printed out?

`
f = print
x = f("hello")
f(type(x))
`

In [59]:
# f = print
x = print("hello")
print(type(x))

hello
<class 'NoneType'>
